name: myclass_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies:
  build_runner: ^2.0.4
  dcli: ^1.5.5
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  puppeteer: ^2.2.0
  sprintf: 6.0.0
